### ISSUE TITLE
need a way to specify ssh key pair 

### ISSUE THREAD

**Issue by cjmatta** [confluentinc/ccloud-tools#10]
I don't see a way to specify my existing key pair, just tried this and can't figure out how to log into any instance.

**Comment by riferrei** [comment]
Hi Chris,

Atl least for AWS, once Terraform completes its job it will create a file named 'cert.pem' in the same folder that holds the AWS implementation. That is what you can use to SSH into the VMs. The outputs will also print out the same information, something like this:

`ssh ec2-user@<PUBLIC_IP_ADDRESS> -i cert.pem`

But that requires you to enable the bastion server in Terraform. Only the bastion server will have inbound access to the VMs created.
