### ISSUE TITLE
kafka-connect missing connectors

### ISSUE THREAD

**Issue by mfly** [confluentinc/ccloud-tools#3]
Due to invalid configuration kafka-connect loads only the `org.apache.kafka.connect.file.FileStreamSinkConnector` (visible by visiting `kafka-connect-url/connector-plugins`).
Temporary fix is to add `plugin.path=/etc/confluent/confluent-5.1.0/share/java` to `/etc/confluent/confluent-5.1.0/etc/kafka-connect/kafka-connect-ccloud.properties`.

**Comment by OneCricketeer** [comment]
Wouldn't exactly consider this a temporary fix. It definitely should be set to the `share/java` absolute path.

**Comment by riferrei** [comment]
Should I add this to the script file that provisions Kafka Connect?

**Comment by riferrei** [comment]
Thanks for the feedback folks. I tested with the entry proposed by @mfly and worked well, therefore I changed the code to include that entry into the kafka-connect.properties. Closing this issue.

Use the last version of the code and you will be good to go ;)

**Comment by OneCricketeer** [comment]
Would it be possible to include an additional folder for additional plugins? Or however `confluent-hub install` manages its installed connectors
