### ISSUE TITLE
confluent.metrics.topic.max.message.bytes

### ISSUE THREAD

**Issue by markteehan** [confluentinc/ccloud-tools#5]
Confluent Cloud has a maximum message size of 8388608 so the default value for confluent.metrics.topic.max.message.bytes of 10485760 causes a C3 infinite reboot loop:

(io.confluent.controlcenter.KafkaHelper)Feb 6 05:31:21 control-center-mcg4 control-center-start: org.apache.kafka.common.errors.PolicyViolationException: Config property 'max.message.bytes' with value '10485760' exceeded max limit of 8388608.Feb 6 05:31:21 control-center-mcg4 control-center-start: [2019-02-06 05:31:21,236] ERROR [main] Startup failed to create necessary topics (io.confluent.controlcenter.KafkaHelper)Feb 6 05:31:21 control-center-mcg4 control-center-start: [2019-02-06 05:31:21,237] INFO [main] Shutting down Kafka Streams 

Please add this line to 
/etc/confluent/confluent-5.1.0/etc/confluent-control-center/c3-ccloud.properties : 

confluent.metrics.topic.max.message.bytes=8388608

**Comment by markteehan** [comment]
See https://confluentinc.atlassian.net/browse/DOCS-1207

**Comment by riferrei** [comment]
Fixed. Thanks for providing the suggestion ;)

**Comment by fahran** [comment]
This tantalising link seems to no longer be public access. Did it used to be?
