### ISSUE TITLE
add interceptors

### ISSUE THREAD

**Issue by markteehan** [confluentinc/ccloud-tools#6]
Connect distributed (properties file kafka-connect-ccloud.properties) should include these two properties to enable Consumer Lag & Data Streams in C3:

producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor

**Comment by riferrei** [comment]
Added!
