### ISSUE TITLE
C3 property confluent.controlcenter.ksql.url must include a port (:8088)

### ISSUE THREAD

**Issue by markteehan** [confluentinc/ccloud-tools#7]
C3 property confluent.controlcenter.ksql.url must include a port (:8088).

At present, kSQL does not start, returning an error message that kSQL is not properly configured.
After modifying the property to add :8088 in /etc/confluent/confluent-5.1.0/etc/confluent-control-center/c3-ccloud.properties and bouncing C3, kSQL then works

**Comment by riferrei** [comment]
Have you tried this again recently? I just tried and without changing anything it works.

If you look the following file:

https://github.com/confluentinc/ccloud-tools/blob/master/terraform/aws/userdata.tf

You're going to see that I set the value of the KSQL Server to include the port as well:

    ksql_server_url = "${join(",", formatlist("http://%s:%s",
      aws_instance.ksql_server.*.private_ip, "8088"))}"

**Comment by riferrei** [comment]
I created a patch by explicit specifying the port 80 from the KSQL LBR.
